service:
  name: IsTodayMeetballsDay

plugins:
  - serverless-webpack
#   - serverless-domain-manager

# custom:
#   customDomain:
#     domainName: "istodaymeatballsday.com"
#     createRoute53Record: true
#     certificateName: "istodaymeatballsday.com"
#     endpointType: 'regional'

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-north-1

functions:
  gui:
    handler: handler.meatballs
    events:
      - http:
          path: /
          method: get
  api:
    handler: api/handler.api
    events:
      - http:
          path: /api
          method: get
