service:
  name: IsTodayMeetballsDay

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-domain-manager

custom:
  customDomain:
    domainName: "istodaymeatballsday.com"
    createRoute53Record: true
    certificateName: "istodaymeatballsday.com"

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-north-1

functions:
  unlock:
    handler: handler.meatballs
    events:
      - http:
          path: /
          method: get
