service:
  name: IsTodayMeetballsDay
  
provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-north-1

functions:
  gui:
    handler: handler.meatballs
    events:
      - http:
          path: /
          method: get